### PR TITLE
Add missing colon

### PR DESCRIPTION
**Pull request by delirious-lettuce**
**Pull Request Label:**
* [x] Bugfix
* [ ] New feature
* [ ] Enhancement
* [ ] Typo

**Pull Request Checklist:**
- [x] Have you followed the [guidelines for contributing](https://github.com/alexanderepstein/cryptowatch/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same fix or component?

-------

### CODE REVIEW

**Comment by alexanderepstein** [comment]
Nice catch!

**Comment by delirious-lettuce** [comment]
@alexanderepstein ,

I'd like to take credit but PyCharm highlighted it in red for me (and it looks like codacy found it too as I was watching the CI check).

**Comment by alexanderepstein** [comment]
I just noticed that codacy picked it up! Maybe I should turn back on the ide feature of atom :smile:

**Comment by delirious-lettuce** [comment]
I haven't used atom much but do whatever you want to do I guess!

**Pull request merged**
